call sp_add_estado("Aguascalientes");
call sp_add_estado("Baja Califorina");
call sp_add_estado("Baja Califorina Sur");
call sp_add_estado("Campeche");
call sp_add_estado('Chiapas', 1);
call sp_add_estado('Chihuahua', 1);
call sp_add_estado('Coahuila', 1);
call sp_add_estado('Colima', 1);
call sp_add_estado('Ciudad de México', 1);
call sp_add_estado('Durango', 1);
call sp_add_estado('Guanajuato', 1);
call sp_add_estado('Guerrero', 1);
call sp_add_estado('Hidalgo', 1);
call sp_add_estado('Jalisco', 1);
call sp_add_estado('México', 1);
call sp_add_estado('Michoacán', 1);
call sp_add_estado('Morelos', 1);
call sp_add_estado('Nayarit', 1);
call sp_add_estado('Nuevo León', 1);
call sp_add_estado('Oaxaca', 1);
call sp_add_estado('Puebla', 1);
call sp_add_estado('Querétaro', 1);
call sp_add_estado('Quintana Roo', 1);
call sp_add_estado('San Luis Potosí', 1);
call sp_add_estado('Sinaloa', 1);
call sp_add_estado('Sonora', 1);
call sp_add_estado('Tabasco', 1);
call sp_add_estado('Tamaulipas', 1);
call sp_add_estado('Tlaxcala', 1);
call sp_add_estado('Veracruz', 1);
call sp_add_estado('Yucatán', 1);
call sp_add_estado('Zacatecas', 1);

select * from tbl_cat_estado;