call sp_add_estado("Aguascalientes", 1);
call sp_add_estado("Baja Califorina", 1);
call sp_add_estado("Baja Califorina Sur", 1);
call sp_add_estado("Campeche", 1);
call sp_add_estado('Chiapas', 1);
call sp_add_estado('Chihuahua', 1);
call sp_add_estado('Coahuila', 1);
call sp_add_estado('Colima', 1);
call sp_add_estado('Ciudad de México', 1);
call sp_add_estado('Durango', 1);
call sp_add_estado('Guanajuato', 1);
call sp_add_estado('Guerrero', 1);
call sp_add_estado('Hidalgo', 1);
call sp_add_estado('Jalisco', 1);
call sp_add_estado('México', 1);
call sp_add_estado('Michoacán', 1);
call sp_add_estado('Morelos', 1);
call sp_add_estado('Nayarit', 1);
call sp_add_estado('Nuevo León', 1);
call sp_add_estado('Oaxaca', 1);
call sp_add_estado('Puebla', 1);
call sp_add_estado('Querétaro', 1);
call sp_add_estado('Quintana Roo', 1);
call sp_add_estado('San Luis Potosí', 1);
call sp_add_estado('Sinaloa', 1);
call sp_add_estado('Sonora', 1);
call sp_add_estado('Tabasco', 1);
call sp_add_estado('Tamaulipas', 1);
call sp_add_estado('Tlaxcala', 1);
call sp_add_estado('Veracruz', 1);
call sp_add_estado('Yucatán', 1);
call sp_add_estado('Zacatecas', 1);

select * from tbl_cat_estado;

call sp_add_municipio("Aguascalientes", 1);
call sp_add_municipio("Asientos", 1);
call sp_add_municipio("Calvillo", 1);
call sp_add_municipio("Cosío", 1);
call sp_add_municipio("Jesús María", 1);
call sp_add_municipio("Pabellón de Arteaga", 1);
call sp_add_municipio("Rincón de Romos", 1);
call sp_add_municipio("San José de Gracia", 1);
call sp_add_municipio("Tepezalá", 1);
call sp_add_municipio("El Llano", 1);

call sp_add_municipio("Ensenada", 2);
call sp_add_municipio("Mexicali", 2);
call sp_add_municipio("Playas de Rosarito", 2);
call sp_add_municipio("Tecate", 2);
call sp_add_municipio("Tijuana", 2);

call sp_add_municipio("Comondú", 3);
call sp_add_municipio("La Paz", 3);
call sp_add_municipio("Loreto", 3);
call sp_add_municipio("Los Cabos", 3);
call sp_add_municipio("Mulegé", 3);

call sp_add_municipio("Calkiní", 4);
call sp_add_municipio("Campeche", 4);
call sp_add_municipio("Carmen", 4);
call sp_add_municipio("Champotón", 4);
call sp_add_municipio("Hecelchakán", 4);
call sp_add_municipio("Hopelchén", 4);
call sp_add_municipio("Palizada", 4);
call sp_add_municipio("Tenabo", 4);
call sp_add_municipio("Escárcega", 4);
call sp_add_municipio("Calakmul", 4);
call sp_add_municipio("Candelaria", 4);

call sp_add_municipio("Acacoyagua", 5);
call sp_add_municipio("Acala", 5);
call sp_add_municipio("Acapetahua", 5);
call sp_add_municipio("Altamirano", 5);
call sp_add_municipio("Amatán", 5);
call sp_add_municipio("Amatenango de la Frontera", 5);
call sp_add_municipio("Amatenango del Valle", 5);
call sp_add_municipio("Angel Albino Corzo", 5);
call sp_add_municipio("Arriaga", 5);
call sp_add_municipio("Bejucal de Ocampo", 5);
call sp_add_municipio("Bella Vista", 5);
call sp_add_municipio("Benemérito de las Américas", 5);
call sp_add_municipio("Berriozábal", 5);
call sp_add_municipio("Bochil", 5);
call sp_add_municipio("El Bosque", 5);
call sp_add_municipio("Cacahoatán", 5);
call sp_add_municipio("Catazajá", 5);
call sp_add_municipio("Cintalapa", 5);
call sp_add_municipio("Coapilla", 5);
call sp_add_municipio("Comitán de Domínguez", 5);
call sp_add_municipio("La Concordia", 5);
call sp_add_municipio("Copainalá", 5);
call sp_add_municipio("Chalchihuitán", 5);
call sp_add_municipio("Chamula", 5);
call sp_add_municipio("Chanal", 5);
call sp_add_municipio("Chapultenango", 5);
call sp_add_municipio("Chenalhó", 5);
call sp_add_municipio("Chiapa de Corzo", 5);
call sp_add_municipio("Chiapilla", 5);
call sp_add_municipio("Chicoasén", 5);
call sp_add_municipio("Chicomuselo", 5);
call sp_add_municipio("Chilón", 5);
call sp_add_municipio("Escuintla", 5);
call sp_add_municipio("Francisco León", 5);
call sp_add_municipio("Frontera Comalapa", 5);
call sp_add_municipio("Frontera Hidalgo", 5);
call sp_add_municipio("La Grandeza", 5);
call sp_add_municipio("Huehuetán", 5);
call sp_add_municipio("Huixtán", 5);
call sp_add_municipio("Huitiupán", 5);
call sp_add_municipio("Huixtla", 5);
call sp_add_municipio("La Independencia", 5);
call sp_add_municipio("Ixhuatán", 5);
call sp_add_municipio("Ixtacomitán", 5);
call sp_add_municipio("Ixtapa", 5);
call sp_add_municipio("Ixtapangajoya", 5);
call sp_add_municipio("Jiquipilas", 5);
call sp_add_municipio("Jitotol", 5);
call sp_add_municipio("Juárez", 5);
call sp_add_municipio("Larráinzar", 5);
call sp_add_municipio("La Libertad", 5);
call sp_add_municipio("Mapastepec", 5);
call sp_add_municipio("Las Margaritas", 5);
call sp_add_municipio("Mazapa de Madero", 5);
call sp_add_municipio("Mazatán", 5);
call sp_add_municipio("Metapa", 5);
call sp_add_municipio("Mitontic", 5);
call sp_add_municipio("Motozintla", 5);
call sp_add_municipio("Nicolás Ruíz", 5);
call sp_add_municipio("Ocosingo", 5);
call sp_add_municipio("Ocotepec", 5);
call sp_add_municipio("Ocozocoautla de Espinosa", 5);
call sp_add_municipio("Ostuacán", 5);
call sp_add_municipio("Osumacinta", 5);
call sp_add_municipio("Oxchuc", 5);
call sp_add_municipio("Palenque", 5);
call sp_add_municipio("Pantelhó", 5);
call sp_add_municipio("Pantepec", 5);
call sp_add_municipio("Pichucalco", 5);
call sp_add_municipio("Pijijiapan", 5);
call sp_add_municipio("El Porvenir", 5);
call sp_add_municipio("Villa Comaltitlán", 5);
call sp_add_municipio("Pueblo Nuevo Solistahuacán", 5);
call sp_add_municipio("Rayón", 5);
call sp_add_municipio("Reforma", 5);
call sp_add_municipio("Las Rosas", 5);
call sp_add_municipio("Sabanilla", 5);
call sp_add_municipio("Salto de Agua", 5);
call sp_add_municipio("San Cristóbal de las Casas", 5);
call sp_add_municipio("San Fernando", 5);
call sp_add_municipio("Siltepec", 5);
call sp_add_municipio("Simojovel", 5);
call sp_add_municipio("Sitalá", 5);
call sp_add_municipio("Socoltenango", 5);
call sp_add_municipio("Solosuchiapa", 5);
call sp_add_municipio("Soyaló", 5);
call sp_add_municipio("Suchiapa", 5);
call sp_add_municipio("Suchiate", 5);
call sp_add_municipio("Sunuapa", 5);
call sp_add_municipio("Tapachula", 5);
call sp_add_municipio("Tapalapa", 5);
call sp_add_municipio("Tapilula", 5);
call sp_add_municipio("Tecpatán", 5);
call sp_add_municipio("Tenejapa", 5);
call sp_add_municipio("Teopisca", 5);
call sp_add_municipio("Tila", 5);
call sp_add_municipio("Tonalá", 5);
call sp_add_municipio("Totolapa", 5);
call sp_add_municipio("La Trinitaria", 5);
call sp_add_municipio("Tumbalá", 5);
call sp_add_municipio("Tuxtla Gutiérrez", 5);
call sp_add_municipio("Tuxtla Chico", 5);
call sp_add_municipio("Tuzantán", 5);
call sp_add_municipio("Tzimol", 5);
call sp_add_municipio("Unión Juárez", 5);
call sp_add_municipio("Venustiano Carranza", 5);
call sp_add_municipio("Villa Corzo", 5);
call sp_add_municipio("Villaflores", 5);
call sp_add_municipio("Yajalón", 5);
call sp_add_municipio("San Lucas", 5);

call sp_add_municipio("Ahumada", 6);
call sp_add_municipio("Aldama", 6);
call sp_add_municipio("Allende", 6);
call sp_add_municipio("Aquiles Serdán", 6);
call sp_add_municipio("Ascensión", 6);
call sp_add_municipio("Bachíniva", 6);
call sp_add_municipio("Balleza", 6);
call sp_add_municipio("Batopilas", 6);
call sp_add_municipio("Bocoyna", 6);
call sp_add_municipio("Buenaventura", 6);
call sp_add_municipio("Camargo", 6);
call sp_add_municipio("Carichí", 6);
call sp_add_municipio("Casas Grandes", 6);
call sp_add_municipio("Coronado", 6);
call sp_add_municipio("Coyame del Sotol", 6);
call sp_add_municipio("La Cruz", 6);
call sp_add_municipio("Cuauhtémoc", 6);
call sp_add_municipio("Cusihuiriachi", 6);
call sp_add_municipio("Chihuahua", 6);
call sp_add_municipio("Chínipas", 6);
call sp_add_municipio("Delicias", 6);
call sp_add_municipio("Dr. Belisario Domínguez", 6);
call sp_add_municipio("Galeana", 6);
call sp_add_municipio("Santa Isabel", 6);
call sp_add_municipio("Gómez Farías", 6);
call sp_add_municipio("Gran Morelos", 6);
call sp_add_municipio("Guachochi", 6);
call sp_add_municipio("Guadalupe", 6);
call sp_add_municipio("Guadalupe y Calvo", 6);
call sp_add_municipio("Guazapares", 6);
call sp_add_municipio("Guerrero", 6);
call sp_add_municipio("Hidalgo del Parral", 6);
call sp_add_municipio("Huejotitán", 6);
call sp_add_municipio("Ignacio Zaragoza", 6);
call sp_add_municipio("Janos", 6);
call sp_add_municipio("Jiménez", 6);
call sp_add_municipio("Juárez", 6);
call sp_add_municipio("Julimes", 6);
call sp_add_municipio("López", 6);
call sp_add_municipio("Madera", 6);
call sp_add_municipio("Maguarichi", 6);
call sp_add_municipio("Manuel Benavides", 6);
call sp_add_municipio("Matachí", 6);
call sp_add_municipio("Matamoros", 6);
call sp_add_municipio("Meoqui", 6);
call sp_add_municipio("Morelos", 6);
call sp_add_municipio("Moris", 6);
call sp_add_municipio("Namiquipa", 6);
call sp_add_municipio("Nonoava", 6);
call sp_add_municipio("Nuevo Casas Grandes", 6);
call sp_add_municipio("Ocampo", 6);
call sp_add_municipio("Ojinaga", 6);
call sp_add_municipio("Praxedis G. Guerrero", 6);
call sp_add_municipio("Riva Palacio", 6);
call sp_add_municipio("Rosales", 6);
call sp_add_municipio("Rosario", 6);
call sp_add_municipio("San Francisco de Borja", 6);
call sp_add_municipio("San Francisco de Conchos", 6);
call sp_add_municipio("San Francisco del Oro", 6);
call sp_add_municipio("Santa Bárbara", 6);
call sp_add_municipio("Satevó", 6);
call sp_add_municipio("Saucillo", 6);
call sp_add_municipio("Temósachic", 6);
call sp_add_municipio("El Tule", 6);
call sp_add_municipio("Urique", 6);
call sp_add_municipio("Uruachi", 6);
call sp_add_municipio("Valle de Zaragoza", 6);

call sp_add_municipio("Abasolo", 7);
call sp_add_municipio("Acuña", 7);
call sp_add_municipio("Allende", 7);
call sp_add_municipio("Arteaga", 7);
call sp_add_municipio("Candela", 7);
call sp_add_municipio("Castaños", 7);
call sp_add_municipio("Cuatro Ciénegas", 7);
call sp_add_municipio("Escobedo", 7);
call sp_add_municipio("Francisco I. Madero", 7);
call sp_add_municipio("Frontera", 7);
call sp_add_municipio("General Cepeda", 7);
call sp_add_municipio("Guerrero", 7);
call sp_add_municipio("Hidalgo", 7);
call sp_add_municipio("Jiménez", 7);
call sp_add_municipio("Juárez", 7);
call sp_add_municipio("Lamadrid", 7);
call sp_add_municipio("Matamoros", 7);
call sp_add_municipio("Monclova", 7);
call sp_add_municipio("Morelos", 7);
call sp_add_municipio("Múzquiz", 7);
call sp_add_municipio("Nadadores", 7);
call sp_add_municipio("Nava", 7);
call sp_add_municipio("Ocampo", 7);
call sp_add_municipio("Parras", 7);
call sp_add_municipio("Piedras Negras", 7);
call sp_add_municipio("Progreso", 7);
call sp_add_municipio("Ramos Arizpe", 7);
call sp_add_municipio("Sabinas", 7);
call sp_add_municipio("Sacramento", 7);
call sp_add_municipio("Saltillo", 7);
call sp_add_municipio("San Buenaventura", 7);
call sp_add_municipio("San Juan de Sabinas", 7);
call sp_add_municipio("San Pedro", 7);
call sp_add_municipio("Sierra Mojada", 7);
call sp_add_municipio("Torreón", 7);
call sp_add_municipio("Viesca", 7);
call sp_add_municipio("Villa Unión", 7);
call sp_add_municipio("Zaragoza", 7);

call sp_add_municipio("Armería", 8);
call sp_add_municipio("Colima", 8);
call sp_add_municipio("Comala", 8);
call sp_add_municipio("Coquimatlán", 8);
call sp_add_municipio("Cuauhtémoc", 8);
call sp_add_municipio("Ixtlahuacán", 8);
call sp_add_municipio("Manzanillo", 8);
call sp_add_municipio("Minatitlán", 8);
call sp_add_municipio("Tecomán", 8);
call sp_add_municipio("Villa de Álvarez", 8);

call sp_add_municipio("Álvaro Obregón", 9);
call sp_add_municipio("Azcapotzalco", 9);
call sp_add_municipio("Benito Juárez", 9);
call sp_add_municipio("Coyoacán", 9);
call sp_add_municipio("Cuajimalpa de Morelos", 9);
call sp_add_municipio("Cuauhtémoc", 9);
call sp_add_municipio("Gustavo A. Madero", 9);
call sp_add_municipio("Iztacalco", 9);
call sp_add_municipio("Iztapalapa", 9);
call sp_add_municipio("Magdalena Contreras", 9);
call sp_add_municipio("Miguel Hidalgo", 9);
call sp_add_municipio("Milpa Alta", 9);
call sp_add_municipio("Tláhuac", 9);
call sp_add_municipio("Tlalpan", 9);
call sp_add_municipio("Venustiano Carranza", 9);
call sp_add_municipio("Xochimilco", 9);

call sp_add_municipio("Canatlán", 10);
call sp_add_municipio("Canelas", 10);
call sp_add_municipio("Coneto de Comonfort", 10);
call sp_add_municipio("Cuencamé", 10);
call sp_add_municipio("Durango", 10);
call sp_add_municipio("General Simón Bolívar", 10);
call sp_add_municipio("Gómez Palacio", 10);
call sp_add_municipio("Guadalupe Victoria", 10);
call sp_add_municipio("Guanaceví", 10);
call sp_add_municipio("Hidalgo", 10);
call sp_add_municipio("Indé", 10);
call sp_add_municipio("Lerdo", 10);
call sp_add_municipio("Mapimí", 10);
call sp_add_municipio("Mezquital", 10);
call sp_add_municipio("Nazas", 10);
call sp_add_municipio("Nombre de Dios", 10);
call sp_add_municipio("Nuevo Ideal", 10);
call sp_add_municipio("Ocampo", 10);
call sp_add_municipio("El Oro", 10);
call sp_add_municipio("Otáez", 10);
call sp_add_municipio("Pánuco de Coronado", 10);
call sp_add_municipio("Peñón Blanco", 10);
call sp_add_municipio("Poanas", 10);
call sp_add_municipio("Pueblo Nuevo", 10);
call sp_add_municipio("Rodeo", 10);
call sp_add_municipio("San Bernardo", 10);
call sp_add_municipio("San Dimas", 10);
call sp_add_municipio("San Juan de Guadalupe", 10);
call sp_add_municipio("San Juan del Río", 10);
call sp_add_municipio("San Luis del Cordero", 10);
call sp_add_municipio("San Pedro del Gallo", 10);
call sp_add_municipio("Santa Clara", 10);
call sp_add_municipio("Santiago Papasquiaro", 10);
call sp_add_municipio("Súchil", 10);
call sp_add_municipio("Tamazula", 10);
call sp_add_municipio("Tepehuanes", 10);
call sp_add_municipio("Tlahualilo", 10);
call sp_add_municipio("Topia", 10);
call sp_add_municipio("Vicente Guerrero", 10);

call sp_add_municipio("Abasolo", 11);
call sp_add_municipio("Acámbaro", 11);
call sp_add_municipio("Apaseo el Alto", 11);
call sp_add_municipio("Apaseo el Grande", 11);
call sp_add_municipio("Atarjea", 11);
call sp_add_municipio("Celaya", 11);
call sp_add_municipio("Comonfort", 11);
call sp_add_municipio("Coroneo", 11);
call sp_add_municipio("Cortazar", 11);
call sp_add_municipio("Cuerámaro", 11);
call sp_add_municipio("Doctor Mora", 11);
call sp_add_municipio("Dolores Hidalgo Cuna de la Independencia Nacional", 11);
call sp_add_municipio("Guanajuato", 11);
call sp_add_municipio("Huanímaro", 11);
call sp_add_municipio("Irapuato", 11);
call sp_add_municipio("Jaral del Progreso", 11);
call sp_add_municipio("Jerécuaro", 11);
call sp_add_municipio("León", 11);
call sp_add_municipio("Manuel Doblado", 11);
call sp_add_municipio("Moroleón", 11);
call sp_add_municipio("Ocampo", 11);
call sp_add_municipio("Pénjamo", 11);
call sp_add_municipio("Pueblo Nuevo", 11);
call sp_add_municipio("Purísima del Rincón", 11);
call sp_add_municipio("Romita", 11);
call sp_add_municipio("Salamanca", 11);
call sp_add_municipio("Salvatierra", 11);
call sp_add_municipio("San Diego de la Unión", 11);
call sp_add_municipio("San Felipe", 11);
call sp_add_municipio("San Francisco del Rincón", 11);
call sp_add_municipio("San José Iturbide", 11);
call sp_add_municipio("San Luis de la Paz", 11);
call sp_add_municipio("Santa Catarina", 11);
call sp_add_municipio("Santa Cruz de Juventino Rosas", 11);
call sp_add_municipio("Santiago Maravatío", 11);
call sp_add_municipio("Silao", 11);
call sp_add_municipio("Tarandacuao", 11);
call sp_add_municipio("Tarimoro", 11);
call sp_add_municipio("Tierra Blanca", 11);
call sp_add_municipio("Uriangato", 11);
call sp_add_municipio("Valle de Santiago", 11);
call sp_add_municipio("Victoria", 11);
call sp_add_municipio("Villagrán", 11);
call sp_add_municipio("Xichú", 11);
call sp_add_municipio("Yuriria", 11);

call sp_add_municipio("Acapulco de Juárez", 12);
call sp_add_municipio("Acatepec", 12);
call sp_add_municipio("Ahuacuotzingo", 12);
call sp_add_municipio("Ajuchitlán del Progreso", 12);
call sp_add_municipio("Alcozauca de Guerrero", 12);
call sp_add_municipio("Alpoyeca", 12);
call sp_add_municipio("Apaxtla", 12);
call sp_add_municipio("Arcelia", 12);
call sp_add_municipio("Atenango del Río", 12);
call sp_add_municipio("Atlamajalcingo del Monte", 12);
call sp_add_municipio("Atlixtac", 12);
call sp_add_municipio("Atoyac de Álvarez", 12);
call sp_add_municipio("Ayutla de los Libres", 12);
call sp_add_municipio("Azoyú", 12);
call sp_add_municipio("Benito Juárez", 12);
call sp_add_municipio("Buenavista de Cuéllar", 12);
call sp_add_municipio("Coahuayutla de José María Izazaga", 12);
call sp_add_municipio("Cocula", 12);
call sp_add_municipio("Copala", 12);
call sp_add_municipio("Copalillo", 12);
call sp_add_municipio("Copanatoyac", 12);
call sp_add_municipio("Coyuca de Benítez", 12);
call sp_add_municipio("Coyuca de Catalán", 12);
call sp_add_municipio("Cuajinicuilapa", 12);
call sp_add_municipio("Cualác", 12);
call sp_add_municipio("Cuautepec", 12);
call sp_add_municipio("Cuetzala del Progreso", 12);
call sp_add_municipio("Cutzamala de Pinzón", 12);
call sp_add_municipio("Chilapa de Álvarez", 12);
call sp_add_municipio("Chilpancingo de los Bravo", 12);
call sp_add_municipio("Florencio Villarreal", 12);
call sp_add_municipio("General Canuto A. Neri", 12);
call sp_add_municipio("General Heliodoro Castillo", 12);
call sp_add_municipio("Huamuxtitlán", 12);
call sp_add_municipio("Huitzuco de los Figueroa", 12);
call sp_add_municipio("Iguala de la Independencia", 12);
call sp_add_municipio("Igualapa", 12);
call sp_add_municipio("Ixcateopan de Cuauhtémoc", 12);
call sp_add_municipio("Zihuatanejo de Azueta", 12);
call sp_add_municipio("Juan R. Escudero", 12);
call sp_add_municipio("Leonardo Bravo", 12);
call sp_add_municipio("Malinaltepec", 12);
call sp_add_municipio("Mártir de Cuilapan", 12);
call sp_add_municipio("Metlatónoc", 12);
call sp_add_municipio("Mochitlán", 12);
call sp_add_municipio("Olinalá", 12);
call sp_add_municipio("Ometepec", 12);
call sp_add_municipio("Pedro Ascencio Alquisiras", 12);
call sp_add_municipio("Petatlán", 12);
call sp_add_municipio("Pilcaya", 12);
call sp_add_municipio("Pungarabato", 12);
call sp_add_municipio("Quechultenango", 12);
call sp_add_municipio("San Luis Acatlán", 12);
call sp_add_municipio("San Marcos", 12);
call sp_add_municipio("San Miguel Totolapan", 12);
call sp_add_municipio("Taxco de Alarcón", 12);
call sp_add_municipio("Tecoanapa", 12);
call sp_add_municipio("Técpan de Galeana", 12);
call sp_add_municipio("Teloloapan", 12);
call sp_add_municipio("Tepecoacuilco de Trujano", 12);
call sp_add_municipio("Tetipac", 12);
call sp_add_municipio("Tixtla de Guerrero", 12);
call sp_add_municipio("Tlacoachistlahuaca", 12);
call sp_add_municipio("Tlacoapa", 12);
call sp_add_municipio("Tlalchapa", 12);
call sp_add_municipio("Tlalixtaquilla de Maldonado", 12);
call sp_add_municipio("Tlapa de Comonfort", 12);
call sp_add_municipio("Tlapehuala", 12);
call sp_add_municipio("La Unión de Isidoro Montes de Oca", 12);
call sp_add_municipio("Xalpatláhuac", 12);
call sp_add_municipio("Xochihuehuetlán", 12);
call sp_add_municipio("Xochistlahuaca", 12);
call sp_add_municipio("Zapotitlán Tablas", 12);
call sp_add_municipio("Zirándaro", 12);
call sp_add_municipio("Zitlala", 12);
call sp_add_municipio("Eduardo Neri", 12);
call sp_add_municipio("Acatepec", 12);
call sp_add_municipio("Marquelia", 12);
call sp_add_municipio("Cochoapa el Grande", 12);

call sp_add_municipio("Acatlán", 13);
call sp_add_municipio("Acaxochitlán", 13);
call sp_add_municipio("Actopan", 13);
call sp_add_municipio("Agua Blanca de Iturbide", 13);
call sp_add_municipio("Ajacuba", 13);
call sp_add_municipio("Alfajayucan", 13);
call sp_add_municipio("Almoloya", 13);
call sp_add_municipio("Apan", 13);
call sp_add_municipio("El Arenal", 13);
call sp_add_municipio("Atitalaquia", 13);
call sp_add_municipio("Atlapexco", 13);
call sp_add_municipio("Atotonilco el Grande", 13);
call sp_add_municipio("Atotonilco de Tula", 13);
call sp_add_municipio("Calnali", 13);
call sp_add_municipio("Cardonal", 13);
call sp_add_municipio("Cuautepec de Hinojosa", 13);
call sp_add_municipio("Chapantongo", 13);
call sp_add_municipio("Chapulhuacán", 13);
call sp_add_municipio("Chilcuautla", 13);
call sp_add_municipio("Eloxochitlán", 13);
call sp_add_municipio("Emiliano Zapata", 13);
call sp_add_municipio("Epazoyucan", 13);
call sp_add_municipio("Francisco I. Madero", 13);
call sp_add_municipio("Huasca de Ocampo", 13);
call sp_add_municipio("Huautla", 13);
call sp_add_municipio("Huazalingo", 13);
call sp_add_municipio("Huehuetla", 13);
call sp_add_municipio("Huejutla de Reyes", 13);
call sp_add_municipio("Huichapan", 13);
call sp_add_municipio("Ixmiquilpan", 13);
call sp_add_municipio("Jacala de Ledezma", 13);
call sp_add_municipio("Jaltocán", 13);
call sp_add_municipio("Juárez Hidalgo", 13);
call sp_add_municipio("Lolotla", 13);
call sp_add_municipio("Metepec", 13);
call sp_add_municipio("San Agustín Metzquititlán", 13);
call sp_add_municipio("Metztitlán", 13);
call sp_add_municipio("Mineral del Chico", 13);
call sp_add_municipio("Mineral del Monte", 13);
call sp_add_municipio("La Misión", 13);
call sp_add_municipio("Mixquiahuala de Juárez", 13);
call sp_add_municipio("Molango de Escamilla", 13);
call sp_add_municipio("Nicolás Flores", 13);
call sp_add_municipio("Nopala de Villagrán", 13);
call sp_add_municipio("Omitlán de Juárez", 13);
call sp_add_municipio("San Felipe Orizatlán", 13);
call sp_add_municipio("Pacula", 13);
call sp_add_municipio("Pachuca de Soto", 13);
call sp_add_municipio("Pisaflores", 13);
call sp_add_municipio("Progreso de Obregón", 13);
call sp_add_municipio("Mineral de la Reforma", 13);
call sp_add_municipio("San Agustín Tlaxiaca", 13);
call sp_add_municipio("San Bartolo Tutotepec", 13);
call sp_add_municipio("San Salvador", 13);
call sp_add_municipio("Santiago de Anaya", 13);
call sp_add_municipio("Santiago Tulantepec de Lugo Guerrero", 13);
call sp_add_municipio("Singuilucan", 13);
call sp_add_municipio("Tasquillo", 13);
call sp_add_municipio("Tecozautla", 13);
call sp_add_municipio("Tenango de Doria", 13);
call sp_add_municipio("Tepeapulco", 13);
call sp_add_municipio("Tepehuacán de Guerrero", 13);
call sp_add_municipio("Tepeji del Río de Ocampo", 13);
call sp_add_municipio("Tepetitlán", 13);
call sp_add_municipio("Tetepango", 13);
call sp_add_municipio("Villa de Tezontepec", 13);
call sp_add_municipio("Tezontepec de Aldama", 13);
call sp_add_municipio("Tianguistengo", 13);
call sp_add_municipio("Tizayuca", 13);
call sp_add_municipio("Tlahuelilpan", 13);
call sp_add_municipio("Tlahuiltepa", 13);
call sp_add_municipio("Tlanalapa", 13);
call sp_add_municipio("Tlanchinol", 13);
call sp_add_municipio("Tlaxcoapan", 13);
call sp_add_municipio("Tolcayuca", 13);
call sp_add_municipio("Tula de Allende", 13);
call sp_add_municipio("Tulancingo de Bravo", 13);
call sp_add_municipio("Xochiatipan", 13);
call sp_add_municipio("Xochicoatlán", 13);
call sp_add_municipio("Yahualica", 13);
call sp_add_municipio("Zacualtipán de Ángeles", 13);
call sp_add_municipio("Zapotlán de Juárez", 13);
call sp_add_municipio("Zempoala", 13);
call sp_add_municipio("Zimapán", 13);

call sp_add_municipio("Acatic", 14);
call sp_add_municipio("Acatlán de Juárez", 14);
call sp_add_municipio("Ahualulco de Mercado", 14);
call sp_add_municipio("Amacueca", 14);
call sp_add_municipio("Amatitán", 14);
call sp_add_municipio("Ameca", 14);
call sp_add_municipio("San Juanito de Escobedo", 14);
call sp_add_municipio("Arandas", 14);
call sp_add_municipio("El Arenal", 14);
call sp_add_municipio("Atemajac de Brizuela", 14);
call sp_add_municipio("Atengo", 14);
call sp_add_municipio("Atenguillo", 14);
call sp_add_municipio("Atotonilco el Alto", 14);
call sp_add_municipio("Atoyac", 14);
call sp_add_municipio("Autlán de Navarro", 14);
call sp_add_municipio("Ayotlán", 14);
call sp_add_municipio("Ayutla", 14);
call sp_add_municipio("La Barca", 14);
call sp_add_municipio("Bolaños", 14);
call sp_add_municipio("Cabo Corrientes", 14);
call sp_add_municipio("Casimiro Castillo", 14);
call sp_add_municipio("Cihuatlán", 14);
call sp_add_municipio("Zapotlán el Grande", 14);
call sp_add_municipio("Cocula", 14);
call sp_add_municipio("Colotlán", 14);
call sp_add_municipio("Concepción de Buenos Aires", 14);
call sp_add_municipio("Cuautitlán de García Barragán", 14);
call sp_add_municipio("Cuautla", 14);
call sp_add_municipio("Cuquío", 14);
call sp_add_municipio("Chapala", 14);
call sp_add_municipio("Chimaltitán", 14);
call sp_add_municipio("Chiquilistlán", 14);
call sp_add_municipio("Degollado", 14);
call sp_add_municipio("Ejutla", 14);
call sp_add_municipio("Encarnación de Díaz", 14);
call sp_add_municipio("Etzatlán", 14);
call sp_add_municipio("El Grullo", 14);
call sp_add_municipio("Guachinango", 14);
call sp_add_municipio("Guadalajara", 14);
call sp_add_municipio("Hostotipaquillo", 14);
call sp_add_municipio("Huejúcar", 14);
call sp_add_municipio("Huejuquilla el Alto", 14);
call sp_add_municipio("La Huerta", 14);
call sp_add_municipio("Ixtlahuacán de los Membrillos", 14);
call sp_add_municipio("Ixtlahuacán del Río", 14);
call sp_add_municipio("Jalostotitlán", 14);
call sp_add_municipio("Jamay", 14);
call sp_add_municipio("Jesús María", 14);
call sp_add_municipio("Jilotlán de los Dolores", 14);
call sp_add_municipio("Jocotepec", 14);
call sp_add_municipio("Juanacatlán", 14);
call sp_add_municipio("Juchitlán", 14);
call sp_add_municipio("Lagos de Moreno", 14);
call sp_add_municipio("El Limón", 14);
call sp_add_municipio("Magdalena", 14);
call sp_add_municipio("Santa María del Oro", 14);
call sp_add_municipio("La Manzanilla de la Paz", 14);
call sp_add_municipio("Mascota", 14);
call sp_add_municipio("Mazamitla", 14);
call sp_add_municipio("Mexticacán", 14);
call sp_add_municipio("Mezquitic", 14);
call sp_add_municipio("Mixtlán", 14);
call sp_add_municipio("Ocotlán", 14);
call sp_add_municipio("Ojuelos de Jalisco", 14);
call sp_add_municipio("Pihuamo", 14);
call sp_add_municipio("Poncitlán", 14);
call sp_add_municipio("Puerto Vallarta", 14);
call sp_add_municipio("Villa Purificación", 14);
call sp_add_municipio("Quitupan", 14);
call sp_add_municipio("El Salto", 14);
call sp_add_municipio("San Cristóbal de la Barranca", 14);
call sp_add_municipio("San Diego de Alejandría", 14);
call sp_add_municipio("San Juan de los Lagos", 14);
call sp_add_municipio("San Julián", 14);
call sp_add_municipio("San Marcos", 14);
call sp_add_municipio("San Martín de Bolaños", 14);
call sp_add_municipio("San Martín Hidalgo", 14);
call sp_add_municipio("San Miguel el Alto", 14);
call sp_add_municipio("Gómez Farías", 14);
call sp_add_municipio("San Sebastián del Oeste", 14);
call sp_add_municipio("Santa María de los Ángeles", 14);
call sp_add_municipio("Sayula", 14);
call sp_add_municipio("Tala", 14);
call sp_add_municipio("Talpa de Allende", 14);
call sp_add_municipio("Tamazula de Gordiano", 14);
call sp_add_municipio("Tapalpa", 14);
call sp_add_municipio("Tecalitlán", 14);
call sp_add_municipio("Tecolotlán", 14);
call sp_add_municipio("Techaluta de Montenegro", 14);
call sp_add_municipio("Tenamaxtlán", 14);
call sp_add_municipio("Teocaltiche", 14);
call sp_add_municipio("Teocuitatlán de Corona", 14);
call sp_add_municipio("Tepatitlán de Morelos", 14);
call sp_add_municipio("Tequila", 14);
call sp_add_municipio("Teuchitlán", 14);
call sp_add_municipio("Tizapán el Alto", 14);
call sp_add_municipio("Tlajomulco de Zúñiga", 14);
call sp_add_municipio("Tlaquepaque", 14);
call sp_add_municipio("Tolimán", 14);
call sp_add_municipio("Tomatlán", 14);
call sp_add_municipio("Tonalá", 14);
call sp_add_municipio("Tonaya", 14);
call sp_add_municipio("Tonila", 14);
call sp_add_municipio("Totatiche", 14);
call sp_add_municipio("Tototlán", 14);
call sp_add_municipio("Tuxcacuesco", 14);
call sp_add_municipio("Tuxcueca", 14);
call sp_add_municipio("Tuxpan", 14);
call sp_add_municipio("Unión de San Antonio", 14);
call sp_add_municipio("Unión de Tula", 14);
call sp_add_municipio("Valle de Guadalupe", 14);
call sp_add_municipio("Valle de Juárez", 14);
call sp_add_municipio("San Gabriel", 14);
call sp_add_municipio("Villa Corona", 14);
call sp_add_municipio("Villa Guerrero", 14);
call sp_add_municipio("Villa Hidalgo", 14);
call sp_add_municipio("Cañadas de Obregón", 14);
call sp_add_municipio("Yahualica de González Gallo", 14);
call sp_add_municipio("Zacoalco de Torres", 14);
call sp_add_municipio("Zapopan", 14);
call sp_add_municipio("Zapotiltic", 14);
call sp_add_municipio("Zapotitlán de Vadillo", 14);
call sp_add_municipio("Zapotlán del Rey", 14);
call sp_add_municipio("Zapotlanejo", 14);

call sp_add_municipio("Acambay", 15);
call sp_add_municipio("Acolman", 15);
call sp_add_municipio("Aculco", 15);
call sp_add_municipio("Almoloya de Alquisiras", 15);
call sp_add_municipio("Almoloya de Juárez", 15);
call sp_add_municipio("Almoloya del Río", 15);
call sp_add_municipio("Amanalco", 15);
call sp_add_municipio("Amatepec", 15);
call sp_add_municipio("Amecameca", 15);
call sp_add_municipio("Apaxco", 15);
call sp_add_municipio("Atenco", 15);
call sp_add_municipio("Atizapán", 15);
call sp_add_municipio("Atizapán de Zaragoza", 15);
call sp_add_municipio("Atlacomulco", 15);
call sp_add_municipio("Atlautla", 15);
call sp_add_municipio("Axapusco", 15);
call sp_add_municipio("Ayapango", 15);
call sp_add_municipio("Calimaya", 15);
call sp_add_municipio("Capulhuac", 15);
call sp_add_municipio("Coacalco de Berriozábal", 15);
call sp_add_municipio("Coatepec Harinas", 15);
call sp_add_municipio("Cocotitlán", 15);
call sp_add_municipio("Coyotepec", 15);
call sp_add_municipio("Cuautitlán", 15);
call sp_add_municipio("Chalco", 15);
call sp_add_municipio("Chapa de Mota", 15);
call sp_add_municipio("Chapultepec", 15);
call sp_add_municipio("Chiautla", 15);
call sp_add_municipio("Chicoloapan", 15);
call sp_add_municipio("Chiconcuac", 15);
call sp_add_municipio("Chimalhuacán", 15);
call sp_add_municipio("Donato Guerra", 15);
call sp_add_municipio("Ecatepec de Morelos", 15);
call sp_add_municipio("Ecatzingo", 15);
call sp_add_municipio("Huehuetoca", 15);
call sp_add_municipio("Hueypoxtla", 15);
call sp_add_municipio("Huixquilucan", 15);
call sp_add_municipio("Isidro Fabela", 15);
call sp_add_municipio("Ixtapaluca", 15);
call sp_add_municipio("Ixtapan de la Sal", 15);
call sp_add_municipio("Ixtapan del Oro", 15);
call sp_add_municipio("Ixtlahuaca", 15);
call sp_add_municipio("Xalatlaco", 15);
call sp_add_municipio("Jaltenco", 15);
call sp_add_municipio("Jilotepec", 15);
call sp_add_municipio("Jilotzingo", 15);
call sp_add_municipio("Jiquipilco", 15);
call sp_add_municipio("Jocotitlán", 15);
call sp_add_municipio("Joquicingo", 15);
call sp_add_municipio("Juchitepec", 15);
call sp_add_municipio("Lerma", 15);
call sp_add_municipio("Malinalco", 15);
call sp_add_municipio("Melchor Ocampo", 15);
call sp_add_municipio("Metepec", 15);
call sp_add_municipio("Mexicaltzingo", 15);
call sp_add_municipio("Morelos", 15);
call sp_add_municipio("Naucalpan de Juárez", 15);
call sp_add_municipio("Nezahualcóyotl", 15);
call sp_add_municipio("Nextlalpan", 15);
call sp_add_municipio("Nicolás Romero", 15);
call sp_add_municipio("Nopaltepec", 15);
call sp_add_municipio("Ocoyoacac", 15);
call sp_add_municipio("Ocuilan", 15);
call sp_add_municipio("El Oro", 15);
call sp_add_municipio("Otumba", 15);
call sp_add_municipio("Otzoloapan", 15);
call sp_add_municipio("Otzolotepec", 15);
call sp_add_municipio("Ozumba", 15);
call sp_add_municipio("Papalotla", 15);
call sp_add_municipio("La Paz", 15);
call sp_add_municipio("Polotitlán", 15);
call sp_add_municipio("Rayón", 15);
call sp_add_municipio("San Antonio la Isla", 15);
call sp_add_municipio("San Felipe del Progreso", 15);
call sp_add_municipio("San Martín de las Pirámides", 15);
call sp_add_municipio("San Mateo Atenco", 15);
call sp_add_municipio("San Simón de Guerrero", 15);
call sp_add_municipio("Santo Tomás", 15);
call sp_add_municipio("Soyaniquilpan de Juárez", 15);
call sp_add_municipio("Sultepec", 15);
call sp_add_municipio("Tecámac", 15);
call sp_add_municipio("Tejupilco", 15);
call sp_add_municipio("Temamatla", 15);
call sp_add_municipio("Temascalapa", 15);
call sp_add_municipio("Temascalcingo", 15);
call sp_add_municipio("Temascaltepec", 15);
call sp_add_municipio("Temoaya", 15);
call sp_add_municipio("Tenancingo", 15);
call sp_add_municipio("Tenango del Aire", 15);
call sp_add_municipio("Tenango del Valle", 15);
call sp_add_municipio("Teoloyucan", 15);
call sp_add_municipio("Teotihuacán", 15);
call sp_add_municipio("Tepetlaoxtoc", 15);
call sp_add_municipio("Tepetlixpa", 15);
call sp_add_municipio("Tepotzotlán", 15);
call sp_add_municipio("Tequixquiac", 15);
call sp_add_municipio("Texcaltitlán", 15);
call sp_add_municipio("Texcalyacac", 15);
call sp_add_municipio("Texcoco", 15);
call sp_add_municipio("Tezoyuca", 15);
call sp_add_municipio("Tianguistenco", 15);
call sp_add_municipio("Timilpan", 15);
call sp_add_municipio("Tlalmanalco", 15);
call sp_add_municipio("Tlalnepantla de Baz", 15);
call sp_add_municipio("Tlatlaya", 15);
call sp_add_municipio("Toluca", 15);
call sp_add_municipio("Tonatico", 15);
call sp_add_municipio("Tultepec", 15);
call sp_add_municipio("Tultitlán", 15);
call sp_add_municipio("Valle de Bravo", 15);
call sp_add_municipio("Villa de Allende", 15);
call sp_add_municipio("Villa del Carbón", 15);
call sp_add_municipio("Villa Guerrero", 15);
call sp_add_municipio("Villa Victoria", 15);
call sp_add_municipio("Xonacatlán", 15);
call sp_add_municipio("Zacazonapan", 15);
call sp_add_municipio("Zacualpan", 15);
call sp_add_municipio("Zinacantepec", 15);
call sp_add_municipio("Zumpahuacán", 15);
call sp_add_municipio("Zumpango", 15);

CALL sp_add_municipio('Acuitzio', 16);
CALL sp_add_municipio('Aguililla', 16);
CALL sp_add_municipio('Álvaro Obregón', 16);
CALL sp_add_municipio('Angamacutiro', 16);
CALL sp_add_municipio('Angangueo', 16);
CALL sp_add_municipio('Apatzingán', 16);
CALL sp_add_municipio('Aporo', 16);
CALL sp_add_municipio('Aquila', 16);
CALL sp_add_municipio('Ario', 16);
CALL sp_add_municipio('Arteaga', 16);
CALL sp_add_municipio('Briseñas', 16);
CALL sp_add_municipio('Buenavista', 16);
CALL sp_add_municipio('Carácuaro', 16);
CALL sp_add_municipio('Coahuayana', 16);
CALL sp_add_municipio('Coalcomán de Vázquez Pallares', 16);
CALL sp_add_municipio('Coeneo', 16);
CALL sp_add_municipio('Contepec', 16);
CALL sp_add_municipio('Copándaro', 16);
CALL sp_add_municipio('Cotija', 16);
CALL sp_add_municipio('Cuitzeo', 16);
CALL sp_add_municipio('Charapan', 16);
CALL sp_add_municipio('Charo', 16);
CALL sp_add_municipio('Chavinda', 16);
CALL sp_add_municipio('Cherán', 16);
CALL sp_add_municipio('Chilchota', 16);
CALL sp_add_municipio('Chinicuila', 16);
CALL sp_add_municipio('Chucándiro', 16);
CALL sp_add_municipio('Churintzio', 16);
CALL sp_add_municipio('Churumuco', 16);
CALL sp_add_municipio('Ecuandureo', 16);
CALL sp_add_municipio('Epitacio Huerta', 16);
CALL sp_add_municipio('Erongarícuaro', 16);
CALL sp_add_municipio('Gabriel Zamora', 16);
CALL sp_add_municipio('Hidalgo', 16);
CALL sp_add_municipio('La Huacana', 16);
CALL sp_add_municipio('Huandacareo', 16);
CALL sp_add_municipio('Huaniqueo', 16);
CALL sp_add_municipio('Huetamo', 16);
CALL sp_add_municipio('Huiramba', 16);
CALL sp_add_municipio('Indaparapeo', 16);
CALL sp_add_municipio('Irimbo', 16);
CALL sp_add_municipio('Ixtlán', 16);
CALL sp_add_municipio('Jacona', 16);
CALL sp_add_municipio('Jiménez', 16);
CALL sp_add_municipio('Jiquilpan', 16);
CALL sp_add_municipio('Juárez', 16);
CALL sp_add_municipio('Jungapeo', 16);
CALL sp_add_municipio('Lagunillas', 16);
CALL sp_add_municipio('Madero', 16);
CALL sp_add_municipio('Maravatío', 16);
CALL sp_add_municipio('Marcos Castellanos', 16);
CALL sp_add_municipio('Lázaro Cárdenas', 16);
CALL sp_add_municipio('Morelia', 16);
CALL sp_add_municipio('Morelos', 16);
CALL sp_add_municipio('Múgica', 16);
CALL sp_add_municipio('Nahuatzen', 16);
CALL sp_add_municipio('Nocupétaro', 16);
CALL sp_add_municipio('Nuevo Parangaricutiro', 16);
CALL sp_add_municipio('Nuevo Urecho', 16);
CALL sp_add_municipio('Numarán', 16);
CALL sp_add_municipio('Ocampo', 16);
CALL sp_add_municipio('Pajacuarán', 16);
CALL sp_add_municipio('Panindícuaro', 16);
CALL sp_add_municipio('Paracho', 16);
CALL sp_add_municipio('Parácuaro', 16);
CALL sp_add_municipio('Pátzcuaro', 16);
CALL sp_add_municipio('Penjamillo', 16);
CALL sp_add_municipio('Peribán', 16);
CALL sp_add_municipio('La Piedad', 16);
CALL sp_add_municipio('Purépero', 16);
CALL sp_add_municipio('Puruándiro', 16);
CALL sp_add_municipio('Queréndaro', 16);
CALL sp_add_municipio('Quiroga', 16);
CALL sp_add_municipio('Cojumatlán de Régules', 16);
CALL sp_add_municipio('Los Reyes', 16);
CALL sp_add_municipio('Sahuayo', 16);
CALL sp_add_municipio('San Lucas', 16);
CALL sp_add_municipio('Santa Ana Maya', 16);
CALL sp_add_municipio('Salvador Escalante', 16);
CALL sp_add_municipio('Senguio', 16);
CALL sp_add_municipio('Susupuato', 16);
CALL sp_add_municipio('Tacámbaro', 16);
CALL sp_add_municipio('Tancítaro', 16);
CALL sp_add_municipio('Tangamandapio', 16);
CALL sp_add_municipio('Tangancícuaro', 16);
CALL sp_add_municipio('Tanhuato', 16);
CALL sp_add_municipio('Taretan', 16);
CALL sp_add_municipio('Tarímbaro', 16);
CALL sp_add_municipio('Tepalcatepec', 16);
CALL sp_add_municipio('Tingambato', 16);
CALL sp_add_municipio('Tingüindín', 16);
CALL sp_add_municipio('Tiquicheo de Nicolás Romero', 16);
CALL sp_add_municipio('Tlalpujahua', 16);
CALL sp_add_municipio('Tlazazalca', 16);
CALL sp_add_municipio('Tocumbo', 16);
CALL sp_add_municipio('Tumbiscatío', 16);
CALL sp_add_municipio('Turicato', 16);
CALL sp_add_municipio('Tuxpan', 16);
CALL sp_add_municipio('Tuzantla', 16);
CALL sp_add_municipio('Tzintzuntzan', 16);
CALL sp_add_municipio('Tzitzio', 16);
CALL sp_add_municipio('Uruapan', 16);
CALL sp_add_municipio('Venustiano Carranza', 16);
CALL sp_add_municipio('Villamar', 16);
CALL sp_add_municipio('Vista Hermosa', 16);
CALL sp_add_municipio('Yurécuaro', 16);
CALL sp_add_municipio('Zacapu', 16);
CALL sp_add_municipio('Zamora', 16);
CALL sp_add_municipio('Zináparo', 16);
CALL sp_add_municipio('Zinapécuaro', 16);
CALL sp_add_municipio('Ziracuaretiro', 16);
CALL sp_add_municipio('Zitácuaro', 16);

CALL sp_add_municipio('Amacuzac', 17);
CALL sp_add_municipio('Atlatlahucan', 17);
CALL sp_add_municipio('Axochiapan', 17);
CALL sp_add_municipio('Ayala', 17);
CALL sp_add_municipio('Coatlán del Río', 17);
CALL sp_add_municipio('Cuautla', 17);
CALL sp_add_municipio('Cuernavaca', 17);
CALL sp_add_municipio('Emiliano Zapata', 17);
CALL sp_add_municipio('Huitzilac', 17);
CALL sp_add_municipio('Jantetelco', 17);
CALL sp_add_municipio('Jiutepec', 17);
CALL sp_add_municipio('Jojutla', 17);
CALL sp_add_municipio('Jonacatepec', 17);
CALL sp_add_municipio('Mazatepec', 17);
CALL sp_add_municipio('Miacatlán', 17);
CALL sp_add_municipio('Ocuituco', 17);
CALL sp_add_municipio('Puente de Ixtla', 17);
CALL sp_add_municipio('Temixco', 17);
CALL sp_add_municipio('Tepalcingo', 17);
CALL sp_add_municipio('Tepoztlán', 17);
CALL sp_add_municipio('Tetecala', 17);
CALL sp_add_municipio('Tetela del Volcán', 17);
CALL sp_add_municipio('Tlalnepantla', 17);
CALL sp_add_municipio('Tlaltizapán de Zapata', 17);
CALL sp_add_municipio('Tlaquiltenango', 17);
CALL sp_add_municipio('Tlayacapan', 17);
CALL sp_add_municipio('Totolapan', 17);
CALL sp_add_municipio('Xochitepec', 17);
CALL sp_add_municipio('Yautepec', 17);
CALL sp_add_municipio('Yecapixtla', 17);
CALL sp_add_municipio('Zacatepec', 17);
CALL sp_add_municipio('Zacualpan de Amilpas', 17);

CALL sp_add_municipio('Acaponeta', 18);
CALL sp_add_municipio('Ahuacatlán', 18);
CALL sp_add_municipio('Amatlán de Cañas', 18);
CALL sp_add_municipio('Bahía de Banderas', 18);
CALL sp_add_municipio('Compostela', 18);
CALL sp_add_municipio('Del Nayar', 18);
CALL sp_add_municipio('Huajicori', 18);
CALL sp_add_municipio('Ixtlán del Río', 18);
CALL sp_add_municipio('Jala', 18);
CALL sp_add_municipio('La Peñita de Jaltemba', 18);
CALL sp_add_municipio('La Yesca', 18);
CALL sp_add_municipio('Rosamorada', 18);
CALL sp_add_municipio('Ruíz', 18);
CALL sp_add_municipio('San Blas', 18);
CALL sp_add_municipio('San José del Valle', 18);
CALL sp_add_municipio('San Pedro Lagunillas', 18);
CALL sp_add_municipio('Santa María del Oro', 18);
CALL sp_add_municipio('Santiago Ixcuintla', 18);
CALL sp_add_municipio('Tecuala', 18);
CALL sp_add_municipio('Tepic', 18);
CALL sp_add_municipio('Tuxpan', 18);
CALL sp_add_municipio('Xalisco', 18);

CALL sp_add_municipio('Abasolo', 19);
CALL sp_add_municipio('Agualeguas', 19);
CALL sp_add_municipio('Los Aldamas', 19);
CALL sp_add_municipio('Allende', 19);
CALL sp_add_municipio('Anáhuac', 19);
CALL sp_add_municipio('Apodaca', 19);
CALL sp_add_municipio('Aramberri', 19);
CALL sp_add_municipio('Bustamante', 19);
CALL sp_add_municipio('Cadereyta Jiménez', 19);
CALL sp_add_municipio('El Carmen', 19);
CALL sp_add_municipio('Cerralvo', 19);
CALL sp_add_municipio('Ciénega de Flores', 19);
CALL sp_add_municipio('China', 19);
CALL sp_add_municipio('Doctor Arroyo', 19);
CALL sp_add_municipio('Doctor Coss', 19);
CALL sp_add_municipio('Doctor González', 19);
CALL sp_add_municipio('Galeana', 19);
CALL sp_add_municipio('García', 19);
CALL sp_add_municipio('San Pedro Garza García', 19);
CALL sp_add_municipio('General Bravo', 19);
CALL sp_add_municipio('General Escobedo', 19);
CALL sp_add_municipio('General Terán', 19);
CALL sp_add_municipio('General Treviño', 19);
CALL sp_add_municipio('General Zaragoza', 19);
CALL sp_add_municipio('General Zuazua', 19);
CALL sp_add_municipio('Guadalupe', 19);
CALL sp_add_municipio('Los Herreras', 19);
CALL sp_add_municipio('Higueras', 19);
CALL sp_add_municipio('Hualahuises', 19);
CALL sp_add_municipio('Iturbide', 19);
CALL sp_add_municipio('Juárez', 19);
CALL sp_add_municipio('Lampazos de Naranjo', 19);
CALL sp_add_municipio('Linares', 19);
CALL sp_add_municipio('Marín', 19);
CALL sp_add_municipio('Melchor Ocampo', 19);
CALL sp_add_municipio('Mier y Noriega', 19);
CALL sp_add_municipio('Mina', 19);
CALL sp_add_municipio('Montemorelos', 19);
CALL sp_add_municipio('Monterrey', 19);
CALL sp_add_municipio('Parás', 19);
CALL sp_add_municipio('Pesquería', 19);
CALL sp_add_municipio('Los Ramones', 19);
CALL sp_add_municipio('Rayones', 19);
CALL sp_add_municipio('Sabinas Hidalgo', 19);
CALL sp_add_municipio('Salinas Victoria', 19);
CALL sp_add_municipio('San Nicolás de los Garza', 19);
CALL sp_add_municipio('Hidalgo', 19);
CALL sp_add_municipio('Santa Catarina', 19);
CALL sp_add_municipio('Santiago', 19);
CALL sp_add_municipio('Vallecillo', 19);
CALL sp_add_municipio('Villaldama', 19);




select * from tbl_cat_municipio;















